name: model-wine-quality
on: [push]
jobs:
  train-model:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
#     container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Train model
        env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data visualization" >> report.md
          cml publish feature_importance.png --md >> report.md
          
          cml send-comment report.md
