name: model-wine-quality
on: [push]
jobs:
  CML-RUN:
    runs-on: windows-latest
#     container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: cml run
        env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip3 install -r requirements.txt
          python train.py
          metrics.txt >> report.md
          cml publish feature_importance.png --md --title "Feature Importance" >> report.md
          cml publish residuals.png --md --title "Residuals" >> report.md          
          cml send-comment report.md
