name: model-wine-quality
on: [push]
jobs:
  train-model:
    runs-on: windows-latest
#     container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Train model
        env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install --upgrade pip
          Python\3.10.4 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          python train.py
          
          type metrics.txt >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-send-comment report.md
